### ISSUE TITLE
Zinc should detect shadowing classes from binary deps by classes from ext deps 

### ISSUE THREAD

**Issue by romanowski** [sbt/zinc#166]
During implementation of https://github.com/sbt/zinc/pull/165 I noticed that if I have project (proj1) with classpath `Seq(scalaJars, proj1_out, proj2_out, jar1.jar)` and jar1.jar contains class foo.Bar and I create class foo.Bar (I know I shouldn't :) ) in proj2_out then zinc will not recompile any sources from proj1 that reference to foo.Bar (but it should).

Other way (change from ext to binary) is (was) supported but is slows down searching for changed classes (see https://github.com/sbt/zinc/pull/165 for more details).

**Comment by romanowski** [comment]
We are creating unit tests for this - PR will be created soon

**Comment by gkossakowski** [comment]
> Other way (change from ext to binary) is (was) supported but is slows down searching for changed classes (see #165 for more details).

What does this mean? Does the "other way" refer to behavior before #165 got merged?

**Comment by romanowski** [comment]
Tests added in https://github.com/sbt/zinc/pull/175 clearly shows that is happens only with analysisOnlyExtDepLookup set to true. I am thinking on reverting https://github.com/sbt/zinc/pull/165

**Comment by eed3si9n** [comment]
Added a test in #179 using actual files, and it seems to be happening without the flag.

**Comment by eed3si9n** [comment]
So we want correctness in terms of respecting classpath, but we also want to avoid looking up classpath all the time. Suppose we have the following classpath:

```
lib/scala-library.jar, sub1/target, sub2/target, lib/sample-binary_2.11-0.1.jar
```

From here I can check whether they have an Analysis associated.

```
None, Some(a1), Some(a2), None
```

And then, we can check the last timestamp. Suppose shadowing of a class happened in `sub2/target` since the last `sub1` compilation it would be:

```
None, Some(t), Some(t + 10s), None
```

This can prompt the duplication check between `sub2/target`'s product and the `lib/sample-binary_2.11-0.1.jar`. If no compilation has happened, then it would be:

```
None, Some(t), Some(t), None
```

This also allows for bump up of JAR version, which still would be:

```
None, Some(t), Some(t), None
```

Can this work?

**Comment by eed3si9n** [comment]
To detect whether shadowing had effect on `sub1`, I'd now need to track `libraryClassNames: Relation[File, String]`. (The relationship named `binaryClassName` exists for different purpose.)

**Comment by romanowski** [comment]
I think the only thing we have to implement is caching here and knownlage from Analysis here.

**Comment by gkossakowski** [comment]
Would `libraryClassNames` track binary dependencies from source files to binary class names?
I think this information is already extracted but not tracked:

``` scala
def addBinaryDeps(src: File, deps: Iterable[(File, String, Stamp)]) =
    new MRelationsNameHashing(srcProd, binaryDep + (src, deps.map(_._1)), internalDependencies = internalDependencies,
      externalDependencies = externalDependencies, classes, names,
      binaryClassName = binaryClassName)
```

Notice how only the first element of triple in `deps` is being used.

Have you considered switching `binaryDep` to tracking binary class names instead of classpath entries (class files or jars)?

**Comment by eed3si9n** [comment]
I have, and I kind of assumed the size is going to be pretty large: all classes going against `scala-library.jar`. Wasn't sure if it's worth it for just this purpose.
