### ISSUE TITLE
Console (Scala REPL) API

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#170]
Port Console API from [sbt-pamflet](https://github.com/sbt/sbt-pamflet/tree/e2e3f496a36578116ca5337ccd303b6b30b33d42/interface/src/main/java/xsbtpamfleti) which abstracts the interaction with REPL.

**Comment by jvican** [comment]
@eed3si9n Can you elaborate on why this should go into Zinc?
  
It's not obvious to me why this should live as a Zinc module given the fact that the REPL is just a cached compiler kept hot by sbt. I think that what it would make more sense is to port it over sbt or use an external module that depends on Zinc and on which sbt depends. What do you think?
  
In case you decide to add this to Zinc, what does this issue require? Is it just a mere port of the code in sbt-pamflet and a few corrections? Or does this issue entail more work than that?

**Comment by eed3si9n** [comment]
> @eed3si9n Can you elaborate on why this should go into Zinc?

### Zinc as sbt module

There are a few points where sbt invokes the Scala compiler. These are compilation, Scaladoc, and Scala REPL. In terms of conceptually splitting sbt up to modules, it makes sense to try to wrap all these under Zinc. With or without incremental compilation, one of the function Zinc provides is a stable API to call Scalac across multiple Scala versions. FWIW there's already https://github.com/sbt/zinc/blob/1.0/internal/compiler-bridge/src/main/scala/xsbt/ConsoleInterface.scala. This case is more about improving it, and exposing it to outside.

### Zinc as library

Since we're going to need to abstract the REPL anyway, it would be convenient to have a public API for it. One usage, as demonstrated by tut and sbt-pamflet is the notion of compiled documentation.

### What's required

First half is probably copying some code over from sbt-pamflet. I think it's about whether we make assumption about you having standard in and out. Second half is exposing it as API.

**Comment by dwijnand** [comment]
:+1: #213 ("Add option to disable incremental compilation") is proof that zinc is used for more than it's incremental compilation feature.

**Comment by jvican** [comment]
Thanks for the explanation @eed3si9n, I see your line of thought now. I'll see what I can do here, but it would be great if we sync in the binary API issue to know what needs to be improved aside from this.

**Comment by jvican** [comment]
I'll comment on the current issue to discuss Zinc's status, or open a new issue, to further discuss what's required. I would need a concrete list of things that need work. I understand that the console API and documenting all the current API is part of the work, but what else? It looks like most of the API lives now in Java land and the design decisions were taken some time ago. With all this information, I'll be able to move waaaaay faster :smile:.

**Comment by jvican** [comment]
This is a ticket for the Scala Center hackathon taking place at Scalasphere 2017.
 
The proposed task is the following: port the Scala REPL interface in sbt-pamflet to Zinc and replace https://github.com/sbt/zinc/blob/1.0/internal/compiler-bridge/src/main/scala/xsbt/ConsoleInterface.scala. The implementation of the Console interface in sbt-pamflet is here: https://github.com/sbt/sbt-pamflet/tree/e2e3f496a36578116ca5337ccd303b6b30b33d42/compiler-bridge/src/main/scala/xsbtpamflet/compilebridge. I suggest that only the implementation of the `ConsoleInterface` is ported over, with all its required dependencies, so that the task is not overwhelming and can be quickly tackled.
  
There is one small test suite here; https://github.com/sbt/sbt-pamflet/blob/e2e3f496a36578116ca5337ccd303b6b30b33d42/sbt-pamflet/src/test/scala/CompilerSpec.scala. It would be great to move it over Zinc and enrich it with more tests, like parsing Scala options and recognising them.

**Comment by jvican** [comment]
This was done in #256, thanks for that! Closing.
