### ISSUE TITLE
Make Analysis content machine-independent

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#218]
There are number of items in Analysis currently that's machine dependent.
We could for example, keep the machine dependent parts such as base directory in-memory, and store relative paths in Analysis. Similar treatment could be done for library JARs, Java Home etc.

Making Analysis content machine-independent allows cached compilation.

**Comment by jvican** [comment]
This is related to #214.
  
I agree this is a nice have. Though I'm not sure we should push for it for the next stable release since it does not affect key functionality in Scala devs workflow. I would suggest marking it as "contributions welcome" or "community" so that people like @gabro could have a stab at it. WDYT @eed3si9n ?

**Comment by gabro** [comment]
@jvican I think it's a good idea, although it'd be great if you guys should provide some extra context/analysis, so that a person not familiar with the code base (like myself) could pick this up.
For instance, do you already have a list of the machine-dependent items?

**Comment by jvican** [comment]
Only paths that I know of. The idea described by @eed3si9n is to have an internal representation that is absolute but only keep relative parts in the serialized analysis instances (and therefore API). An internal conversion relative -> absolute -> relative would need to be performed (the first one to read analysis and the second one to write it).
  
Classpaths would need special handling (we need to be careful, some of the paths in classpaths are absolute and therefore machine-dependent). Those should be left unchanged. We should only change paths that affect user-defined class files or jars.

**Comment by eed3si9n** [comment]
Lightbend and @romanowski (VirtusLab) has spent some time thinking about this problem, so I think it's something one of us should tackle. Analysis structure is among the most critical aspect of Zinc to get right.

**Comment by jvican** [comment]
Good @eed3si9n, that makes sense! I'll focus for now on the dependency analysis, but if I have time left I'll try to get it out. Though I would prefer if someone else (perhaps @romanowski) is interested in tackling this soon.

**Comment by romanowski** [comment]
First of all we need to make both *Analysis* and *MInisetup* machine independent. 
Zinc (in current shape) is IMO way too low level to handle relative classpath or even relative source roots.

Classpath is good example here since build tool (e.g. sbt) knows what makes given classpath entry. We can map e.g. jar back to its declaration (so e.g. /my/absolute/path/lib.jar becomes ogranization%name%version%jar that we can share across machines).

However zinc can allows clients to make analysis machine independent. All what is required to achieve that is already implemented in #216 as mappers (so client can map part of Analysis based of its setup).

I am working on client (plugin for sbt) based on that idea (https://github.com/romanowski/hoarder) for both 1.0 and 0.13. As said in PR we are now not open source integration that reusing analysis between different machines (it includes different build tools and operating systems).

**Comment by jvican** [comment]
@romanowski I won't assign any cycles to this. Are you thinking of implementing it?

**Comment by romanowski** [comment]
I my opinion this should not be implemented inside zinc and as [Hoarder](https://github.com/romanowski/hoarder) shows it can be done outside quite easily. So I think we should either close this issue or move it down in priority queue.

**Comment by jvican** [comment]
That sounds good to me. The fact that we can outsource this kind of functionality is very beneficial to Zinc maintenance, since I do not expect this one to be easy to implement. You're doing crazy progress on Hoarder, hope to see that feature implemented there.
  
What do other maintainers think about this? I'm for closing this issue.
  
@gabro If you're interested in this, you should probably reach out to @romanowski and talk about potential ways of collaborating. I'm sure he'll help you out! :smile:

**Comment by romanowski** [comment]
@gabro I've got planty od ideas how [Hoarder](https://github.com/romanowski/hoarder)'s engine can be used and the only thing I lack is time. Any help appreciated!

**Comment by eed3si9n** [comment]
I suspect certain parts of Zinc is still machine-dependent as long as we depend on Java serialization, which I think sbinary codecs do sometimes.

**Comment by dwijnand** [comment]
I think we should keep this open, even at low priority: just because it can done externally doesn't mean that all clients much always be burden by this.

I've not looked at the details properly but I fail to understand how @romanowski can claim that "it can be done outside quite easily" while @jvican states "I do not expect this one to be easy to implement". Something doesn't add up... :-D

**Comment by romanowski** [comment]
There is one thing that we miss in zinc: context. Example: if you got sources (and we get sources as an array): ```/my/path/root1/pck1/Ala.scala, /my/path/root1/pck2/Ala.scala, /my/path/root2/pck1/Ala.scala``` then you can't tell where is your sources roots are (but if you use context from e.g. sbt becomes quite simple).

**Comment by jvican** [comment]
We may want to keep this open and fix it upstream to help Pants and other build tools that need this. (/cc @stuhood @peiyuwang).

**Comment by stuhood** [comment]
In our experience distributing zinc's analysis across Linux and OSX machines in [pants' cache](http://www.pantsbuild.org/setup_repo.html#build-cache), the only thing that is necessary to rewrite are filenames.

In particular, we have a single "sourceroot" for all input sources (the root of the repository), and a single "workdir" (usually `$root/.pants.d/`) for all binary outputs. We relativize all paths inside the analysis to those two bases when we put an entry in the cache, and rewrite it when we take an entry from the cache.

The reason there are two paths (rather than just a single "repo base") is to support locating the binary outputs directory outside of the repo, which can help in deployment models that put compile outputs in a ramdisk, for example.

One notable thing that pants does is to symlink out of the ivy (or coursier) cache and into the "workdir", in order to guarantee that all inputs can be relativized to one of the two directories.

**Comment by jvican** [comment]
> single "workdir" (usually $root/.pants.d/) for all binary outputs. We relativize all paths inside the analysis to those two bases when we put an entry in the cache, and rewrite it when we take an entry from the cache.
  
Sbt has several workdirs, but I think achieving this is doable.
  
> locating the binary outputs directory outside of the repo, which can help in deployment models that put compile outputs in a ramdisk
  
Do you place compile outputs in a ramdisk? I would be interested to know what speedups you get.
  
> One notable thing that pants does is to symlink out of the ivy (or coursier) cache and into the "workdir", in order to guarantee that all inputs can be relativized to one of the two directories.
  
This is a good solution for the problem. I think we could experiment with it. I don't see any reason why we couldn't do the same with sbt. However, this will require us to place some logic in sbt/sbt instead of sbt/zinc.
  
Thanks for sharing @stuhood.

**Comment by romanowski** [comment]
This is more or less what I am doing in Hoarder.
@stuhood How do you rewrite paths? I recommend using [AnalysisMappers](https://github.com/sbt/zinc/blob/1.0/internal/zinc-persist/src/main/scala/sbt/internal/inc/AnalysisMappers.scala#L71-L108)

**Comment by stuhood** [comment]
@romanowski : Neat. A long while ago (and thus potentially no-longer-relevant) we found that fully deserializing analysis in order to rewrite it was much more expensive than doing line-oriented rewrites... and so we're currently using a python line-oriented implementation.

But since AnalysisMappers looks like it could be used on the fly while saving analysis, I'm guessing it would solve the problem of redundant serialization.

**Comment by jvican** [comment]
Fixed in #351. Analysis is now machine independent provided that build tools implement `ReadMapper` and `WriteMapper`. These mappers are used after reading and before writing, respectively. If you want to see an example, have a look at https://github.com/sbt/zinc/blob/3026ea8f57ecf18e5fa93f9f2fe7542e5174e2f5/internal/zinc-persist/src/main/scala/sbt/internal/inc/mappers/RelativeReadMappers.scala.
