### ISSUE TITLE
License source headers in Zinc

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#222]
I've seen that some sources have license headers. For instance, `Dependency.scala`:
```scala
/* sbt -- Simple Build Tool
 * Copyright 2008, 2009 Mark Harrah
 */
```
  
I'd like to know how licensing works in this Zinc project. I think I'm supposed to also put my credentials as Mark Harrah has done in every new source file I create, but I'm not sure. Also, I've seen that this project is governed by the Lightbend license and some contributions from other people are licensed under other compatible licenses (like @romanowski has been doing in his last PRs).
  
Could someone explain me how this works? Thanks.

**Comment by eed3si9n** [comment]
Thanks for bring it up. I haven't been super clear about the license of Zinc.
When sbt was first created by Mark, it was under his and contributors copyright, and was released under BSD. Currently sbt and by extension Zinc is under Lightbend's copyright, and we require copyright reassignment via [Lightbend CLA](https://www.lightbend.com/contribute/cla).
I should take this opportunity to reassign Zinc under Apache v2, and put headers on all sources.

**Comment by jvican** [comment]
Yes, please, do. I think that this should also be explained in a CONTRIBUTING file, along with some conventions of what to do in case new files are created.
  
To the best of my knowledge, then, contributions to this Apache project will allow contributors to relicense their contributions under compatible Apache licenses, as @romanowski has done. Please, correct me if I'm wrong, I'm not a license guru.

**Comment by smarter** [comment]
>  I should take this opportunity to reassign Zinc under Apache v2, and put headers on all sources.

I'm not a big fan of that. All of the core Scala projects are under BSD, re-licensing an existing core part of the Scala infrastructure under another license is likely to introduce confusion. It can also have ripple effects, if I want to import changes from the Zinc compiler bridge into the dotty compiler bridge, I would have to relicense part (or all) of dotty to Apache 2, same with scalac if the idea to make the compiler bridge part of scalac is either implemented.

**Comment by eed3si9n** [comment]
ok. Never mind Apache v2 then. /cc @adriaanm

**Comment by adriaanm** [comment]
I don't know how to reason with confidence about mixing these licenses in a code base, so I'd also rather avoid it, even though it's probably possible if we had to.

**Comment by dwijnand** [comment]
From my basic understanding, the licenses are both permissive and just
require some minimal work, like file header license/copyright attribution
when reusing. I think aligning the release license with the SLA is a worthy
goal to pursue.

**Comment by fommil** [comment]
@smarter when contributing to Scala or Dotty you are supposed to declare it to be your original invention AND sign the Apache 2.0 contributor agreement with EPFL as the counterparty (aka the SLA).

You need an exception from EPFL to contribute in any other way (see section 7). I'm sure people have accidentally done this the wrong way many times already, because there is not a lot of process around it.

Taking MIT or BSD code that you didn't write, and putting it in scala/dotty is completely against the SLA, because it means that you don't have the legal right to sign the Grant of Patent clause (section 3 and probably 4).

Zinc being Apache 2.0 puts you on a stronger footing if you want to contribute code that you did not write, because the CLA has in effect been signed by everybody who contributed on that basis. But, yes, scala/dotty would then have to provide the LICENSE and COPYING files from Zinc, and header information on the files copied. (There is a small caveat, which is that code contributed to Zinc before it was published under the Apache 2.0 does not include the Grant of Patent, so you're back to the same situation as contributing BSD code to scala).

**Comment by smarter** [comment]
> Taking MIT or BSD code that you didn't write, and putting it in scala/dotty is completely against the SLA, because it means that you don't have the legal right to sign the Grant of Patent clause (section 3 and probably 4).

Good point, though in the case of zinc and scala/dotty, the CLA is the same, so it should be fine.

**Comment by eed3si9n** [comment]
For now, I'm going to propose the following header:

```
/* Zinc - The incremental compiler for Scala.
 * Copyright 2011 - 2017, Lightbend, Inc.
 * Copyright 2008 - 2010, Mark Harrah
 * This software is released under the terms written in LICENSE.
 */
```

**Comment by fommil** [comment]
@smarter aha, no it is not! This is exactly the point that I tried to raise with the Scala Center, but they dismissed it because it would involve getting EPFL lawyers involved (even though it is actually fundamental to how we share code).

Although scala contributors sign the Apache CLA (aka SLA) when contributing to Scala, EPFL only release it under the BSD. Similarly, contributors sign something-like-Apache-CLA when contributing to Lightbend projects, but it is only released under the BSD. This is not the Apache CLA because they added some extra, geographically restrictive, clauses. Incidentally, if this were the license that Lightbend used to distribute their software, it would be GPL incompatible and I'd have to give up on all my libre project (notably ENSIME), and possibly scala too.

Zinc is distributed under BSD, but contributions are accepted under Typesafe CLA... I'm not even sure if Lightbend can legally contribute that code to Scala because of the "laws of the state of California" clause, unless they want to be a bit gung ho about it all. There is an argument that once they have all the patent rights, they can then "undo" the California clause and release under Apache, but that's one for lawyers.

**Comment by eed3si9n** [comment]
1. As a consumer of Scala, the community can enjoy the free-ness of BSD with two rights holders EPFL *and* Lightbend.
2. As a contributor to Scala, some must reassign their copyrights and grant patent to EPFL (and recipients of software distributed by EPFL) via Scala CLA.

Similarly Zinc is owned by Mark Harrah and Lightbend, and CLA goes to Lightbend. I'm not sure about others, but Lightbend sure should be able to migrate Zinc code out to Scala.

**Comment by fommil** [comment]
1. BSD is not as free/libre as Apache 2.0. There is still the legal risk to scala users that EPFL (e.g. the commercialisation department, out of the control of the scala academics) or Lightbend (e.g. a future asset-stripping investor) can request patent payments from consumers. Of course, there need to be patents to do this. EPFL are most definitely in the business of filing worldwide software patents, whereas Typesafe / Lightbend may not be. This is what Oracle are now attempting to do with Java.
2. "and recipients of software distributed by EPFL" this may be what the contributor signs, but it is not what EPFL then grant to the scala users. EPFL only gives the BSD to consumers, and definitely not the patent clause --- this has been explicitly mentioned in the Scala Center minutes and is intentional, to avoid having to get EPFL lawyers involved. Also, the Scala CLA is not copyright reassignment, it is a license from the author to the EPFL. The author still retains the copyright and can release it under whatever license they choose in another project.

You're probably right that Lightbend can migrate code (contributed under the Lightbend CLA) to Scala, but for anything Mark wrote prior to the CLA being in place, you have to trust that he holds no patents (I assume Lightbend have done the check... I'd be pretty surprised if he had any!).
