### ISSUE TITLE
Make sure the compile order situation is clear in the documentation

### ISSUE THREAD

**Issue by dwijnand** [sbt/zinc#235]
`MixedAnalyzingCompiler` (which I believe is the default compiler used) doesn't distinguish the behaviour between `ScalaThenJava` and `Mixed`.

See #234 for the previous discussion around this.

We should try and make this clear, by changing the docs.

Even better would be to make it obvious by removing one or the other. But that involves deprecation cycles, so lets make it clear for now.

**Comment by jvican** [comment]
Thanks for filing this per our previous discussion Dale!

**Comment by jvican** [comment]
I'm already working on documenting this part of the API.

**Comment by jvican** [comment]
The current documentation says that Mixed mode allows Scala sources to depend on Java sources and allows Java sources to depend on Scala sources.
  
It happens that the implementation `ScalaThenJava` fits the `Mixed` semantics correctly thanks to Scalac (and Dotty, in the future). The Scala compiler parses any Java source and populate the symbol table (therefore allowing Scala sources to depend on Java sources), and then after Scala has generated the class files, Zinc will invoke javac with those generated class files in the classpath (therefore allowing Java to depend on Scala). However, the fact that Scalac works this way is just a design decision, and this is an implementation detail of the compiler that could change in the future (to be honest, the likelihood of this changing is quite low).
  
Because of this, I suggest that we don't remove `Mixed`, we should only improve documentation and make the situation clearer. To be honest, I think that keeping `Mixed` is good for the end user, because `ScalaThenJava` has a very clear meaning, and people may end up now knowing that it covers the case of `Mixed`. What should we do? 
  
For clarification, see @smarter's comments [here](https://github.com/sbt/zinc/issues/234).

**Comment by jvican** [comment]
Okay, after giving it some more thought: it makes sense to leave `Mixed` because it has a conceptual difference regarding `ScalaThenJava`. The difference would come in the way Zinc handles the options passes to the Scala compiler. Under `Mixed` you would pass both Scala and Java sources, while under `ScalaThenJava` you would only pass Scala sources and leave the Java sources to be compiled by the Java compiler.
  
This whole discussion boils down to the fact that the implementation [here](https://github.com/sbt/zinc/blob/1.0/zinc/src/main/scala/sbt/internal/inc/MixedAnalyzingCompiler.scala#L70) is the same for both. But to my understanding Zinc is applying the logic described in the previous paragraph before arriving to the `MixedAnalyzingCompiler`, so we're safe.
  
I thereby propose to leave `Mixed` the way it is. /cc @dwijnand

**Comment by jvican** [comment]
In the PR fixing the binary API that I'm currently working on, I've written this documentation:
```java
/*
 * Zinc - The incremental compiler for Scala.
 * Copyright 2011 - 2017, Lightbend, Inc.
 * Copyright 2008 - 2010, Mark Harrah
 * This software is released under the terms written in LICENSE.
 */

package xsbti.compile;

/**
 * Define the order in which Scala and Java compilation should happen.
 *
 * This compilation order matters when the sources to be compiled are both
 * Scala and Java sources, in which case the Zinc compiler needs a strategy
 * to deal with the compilation order. Therefore, this setting has no effect
 * if only Java or Scala sources are being compiled.
 */
public enum CompileOrder {
	/**
	 * Allow Scala sources to depend on Java sources and allow Java sources to
	 * depend on Scala sources.
     *
	 * Under this mode, both Java and Scala sources can depend on each other.
	 * Java sources are also passed to the Scala compiler, which parses them,
	 * populates the symbol table and lifts them to Scala trees without
	 * generating class files for the Java trees.
	 *
	 * Then, the incremental compiler will add the generated Scala class files
	 * to the classpath of the Java compiler so that Java sources can depend
	 * on Scala sources.
     *
	 * For more information on the way Mixed and ScalaThenJava mode behave,
	 * see <a href="https://github.com/sbt/zinc/issues/235">this link</a>.
	 */
	Mixed,

	/**
	 * Allow Scala sources to depend on the Java sources, but it does not allow
	 * Java sources to depend on Scala sources.
     *
	 * When mixed compilation is not required, it's generally more efficient
	 * {@link CompileOrder#JavaThenScala} than {@link CompileOrder#ScalaThenJava}
	 * because the Scala compiler will not parse Java sources, it will just
	 * unpickle the symbol information from class files.
	 */
	JavaThenScala,

	/**
     * Allow Java sources to depend on Scala sources, but it does not allow Java
	 * sources to depend on Scala sources.
     *
     * Because of the way the Scala compiler works with regard to Java sources,
	 * Zinc has to enforce this mode by removing Java sources from the actual
	 * source arguments that are passed to the Scala compiler, otherwise it'll
	 * behave exactly as {@link CompileOrder#Mixed}.
	 *
	 * For more information on the way Mixed and ScalaThenJava mode behave,
	 * see <a href="https://github.com/sbt/zinc/issues/235">this link</a>.
	 */
	ScalaThenJava
}
```

**Comment by dwijnand** [comment]
The existing docs are (non-obviously) wrong (copy-paste):

https://github.com/sbt/sbt/blob/v0.13.13/interface/src/main/java/xsbti/compile/CompileOrder.java

Yet people have opted into specific settings:

https://github.com/search?l=Scala&q=compileOrder&type=Code&utf8=%E2%9C%93

(https://github.com/sbt/sbt/commit/03ba47c58c6dad710f66e72e4c7c7b73d9b12bf7#commitcomment-1014692 :D)

---

>
 	 * When mixed compilation is not required, it's generally more efficient
	 * {@link CompileOrder#JavaThenScala} than {@link CompileOrder#ScalaThenJava}
	 * because the Scala compiler will not parse Java sources, it will just
	 * unpickle the symbol information from class files.

Is it faster to unpickle than parse?

---

WRT everything you said @jvican: I agree, LGTM, and good work.

**Comment by jvican** [comment]
Yes, it's faster because of two things: you don't waste memory to store Java trees, and unpickling is lazy, so if you only use Java symbols you will ignore the unused symbols and not execute them.
  
In any case, that remark was already there when I arrived. Happy to be convinced otherwise, but that's my justification of why it's faster. I'm not an expert in this area.

**Comment by jvican** [comment]
This was already merged long time ago, so closing.
