### ISSUE TITLE
Zinc is undercompiling in case of type projection where Scalac expands to another type

### ISSUE THREAD

**Issue by romanowski** [sbt/zinc#269]
In case included in #270 zinc is undercompiling.

I don't get to the bottom of problem (yet) but I think this is caused by the way how we handle type fields.

**Comment by eed3si9n** [comment]
This looks like a variation of As-seen-from issue #174, which I thought was fixed in https://github.com/sbt/zinc/pull/239

**Comment by romanowski** [comment]
Agree, but here types are much more complicated. I forgot to add: this issue was found on production code.

**Comment by jvican** [comment]
Hey @romanowski, thanks for reporting this.
  
Even though it looks like an as seen from issue, it's not. My analysis reveals that the prefix `FactoryProvider` is totally lost at `Usage` after typer. This is one of these cases where Scalac is expanding types and not leaving any trace to keep track of the original dependency.  `FactoryProvider.type#MyFactory#Product` becomes `foo.B with foo.Nil#Product`.
  
So, the solution to this problem is to traverse the original tree in `Dependency`. This is fixed in https://github.com/sbt/zinc/pull/272.

**Comment by romanowski** [comment]
@jvican Thanks for fixing it so fast!
