### ISSUE TITLE
Provide nailgun integration for Zinc

### ISSUE THREAD

**Issue by eyalroth** [sbt/zinc#299]
Please add a built-in method to run Zinc server in the background on a Windows environment, preferably with an option to start the server on Windows login (say, a service).

My current workaround is quite messy; I have one .bat which runs the server via Git Bash (using the Unix command to start the server), and then another .bat which calls the first .bat from Windows startup directory, which leaves an open cmd window at the end (couldn't work around that).

**Comment by jvican** [comment]
Hey @eyalroth, thanks for opening this ticket. This is an interesting feature request that can be implemented with nailgun. I think this is worth it, and I envision sbt even using it in the long term. But first it needs to prove successful and feasible. On a cursory look, I see two main benefits:
  
1. Stability. The scala compiler has its own JVM. Good for better JIT (and code caches). This way we don't risk destabilizing the JIT and deoptimizing/optimizing too much (I feel that running the scala compiler in the same JVM as the build tool -- sbt -- is a performance bottleneck). I need data to prove it, though.
2. Reusability. Any other sbt or instance can reuse it.
  
However, we need to figure out what the workflow would be for your case, since it's not clear that sbt's use case and your use case are the same. Can you elaborate on what would be the ideal workflow for you? The more details, the better.

**Comment by eyalroth** [comment]
Well, I have no functional need of Zinc other than improving build compilation times. I'm actually using Maven, not sbt, and I'm developing my Scala code with IntelliJ. Most of the time I compile using IntelliJ, which is a bit sketchy, but sometimes I also need to build my entire Maven project (with Maven that is), which may take quite some time.

I was able to find a better workaround, and that is to create a custom service using Windows NT Resource Kit (or http://nssm.cc/) for my .bat file (which runs the Zinc server via Git Bash).

**Comment by jvican** [comment]
This is clearly out of scope of this repository :smile:. Now it already exists, and it's called bloop https://github.com/scalacenter/bloop.

**Comment by eyalroth** [comment]
I didn't know about Bloop. I'd definitely be interested in integrating it in my project, though in the meanwhile I moved to Gradle 😆.
