### ISSUE TITLE
Add support for fine-grained builds

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#306]
@stuhood comments in https://contributors.scala-lang.org/t/asking-for-your-feedback-on-sbt-scala-center-announcement/738/20?u=jvican that Zinc overhead could be hurting compilation of fine-grained builds. This is presumably caused by Zinc being too slow to start up.
  
In this ticket, I would like to investigate how big this overhead is and, if significant, how to decrease it so that the compilation of lots of modules is not dominated by Zinc start up times.
  
I see two related issues:
  
1. Add nailgun integration for Zinc: https://github.com/sbt/zinc/issues/299. Though I suspect Pants already has its own, can you confirm @stuhood?
2. Speed up the analysis serialization/deserialization, i.e. https://github.com/sbt/zinc/issues/268. I have interesting insights to share with all in that ticket, so I'll update it soon.
  
I'll be updating this ticket as soon as I have some numbers and precise insights on what could be hurting startup time.

**Comment by stuhood** [comment]
Yes, pants already has its own nailgun integration.

**Comment by romanowski** [comment]
my 2 cents since we've also faced similar problems:
* classpath modification dates caching: zinc checks modification dates for all jars on classpath. In case of big number of small modules this may take quite a lot of time. We've workaround this by using [ExternalHooks](https://github.com/sbt/zinc/blob/1.0/internal/compiler-interface/src/main/java/xsbti/compile/ExternalHooks.java) and caching modification dates (so all is checked only once per build)
* In intellij we've got Nailgun in place so 2) is not hurting us that much but serialization takes quite a while

**Comment by jvican** [comment]
@romanowski Can you share your setup for Nailgun in Intellij? I'm really interested to see how you've done it.

**Comment by romanowski** [comment]
Sure, but I cannot promise when (before code need to be cleaned up since we've got too many project-specific stuff merged).

**Comment by dwijnand** [comment]
I'm going to close this as it would seem that keeping an instance of Zinc up (perhaps with nailgun or Bloop) is what people are happy to do.  Also the related issues are now closed.
