### ISSUE TITLE
Better API for custom ClassfileManager

### ISSUE THREAD

**Issue by smarter** [sbt/zinc#312]
sbt 0.13:
```scala
  def dottyPatchIncOptions(incOptions: IncOptions): IncOptions = {
    val inheritedNewClassfileManager = incOptions.newClassfileManager
    val newClassfileManager = () => new ClassfileManager {
      private[this] val inherited = inheritedNewClassfileManager()

      def delete(classes: Iterable[File]): Unit = {
        val tastySuffixes = List(".tasty", ".hasTasty")
        inherited.delete(classes flatMap { classFile =>
          val dottyFiles = if (classFile.getPath endsWith ".class") {
            val prefix = classFile.getAbsolutePath.stripSuffix(".class")
            tastySuffixes.map(suffix => new File(prefix + suffix)).filter(_.exists)
          } else Nil
          classFile :: dottyFiles
        })
      }

      def generated(classes: Iterable[File]): Unit = inherited.generated(classes)
      def complete(success: Boolean): Unit = inherited.complete(success)
    }
    incOptions.withNewClassfileManager(newClassfileManager)
  }
```

sbt 1.0:
```scala
  // Copy-pasted from sbt where it's private
  private case class WrappedClassFileManager(internal: ClassFileManager,
                                             external: Option[ClassFileManager])
      extends ClassFileManager {

    override def delete(classes: Array[File]): Unit = {
      external.foreach(_.delete(classes))
      internal.delete(classes)
    }

    override def complete(success: Boolean): Unit = {
      external.foreach(_.complete(success))
      internal.complete(success)
    }

    override def generated(classes: Array[File]): Unit = {
      external.foreach(_.generated(classes))
      internal.generated(classes)
    }
  }

  def dottyPatchIncOptions(incOptions: IncOptions): IncOptions = {
    val inheritedNewClassFileManager = ClassFileManagerUtil.getDefaultClassFileManager(incOptions)
    val tastyFileManager = new ClassFileManager {
      private[this] val inherited = inheritedNewClassFileManager

      def delete(classes: Array[File]): Unit = {
        val tastySuffixes = List(".tasty", ".hasTasty")
        inherited.delete(classes flatMap { classFile =>
          if (classFile.getPath endsWith ".class") {
            val prefix = classFile.getAbsolutePath.stripSuffix(".class")
            tastySuffixes.map(suffix => new File(prefix + suffix)).filter(_.exists)
          } else Nil
        })
      }

      def generated(classes: Array[File]): Unit = {}
      def complete(success: Boolean): Unit = {}
    }
    val inheritedHooks = incOptions.externalHooks
    val hooks = new ExternalHooks {
      override def externalClassFileManager() = Option(inheritedHooks.externalClassFileManager.orElse(null)) match {
        case Some(prevManager) =>
          Optional.of(WrappedClassFileManager(prevManager, Some(tastyFileManager)))
        case None =>
          Optional.of(tastyFileManager)
      }
      override def externalLookup() = inheritedHooks.externalLookup()
    }
    incOptions.withExternalHooks(hooks)
  }
```

I assume that for sbt 2.0 we will need 1000 lines of code to do this :).

**Comment by sjrd** [comment]
I can't help but wonder what was wrong with the 0.13 API to begin with? It thought that API was quite nice when I first solved the delete-the-`.sjsir` files issue in Scala.js 0.1. Can't we simply go back to that API in sbt 1.0? What prompted the change?

**Comment by jvican** [comment]
You must ask this question to the person that designed it in the first place. That is not me. I will look into ways of simplifying it before the RC.

**Comment by sjrd** [comment]
@jvican I'm not asking to anyone in particular. I expect "the person that designed it in the first place" to be a follower of this repo and chime in on their own.

**Comment by jvican** [comment]
The first solution here would be to expose `WrappedClassFileManager` in the public API:
```
  // Copy-pasted from sbt where it's private
  private case class WrappedClassFileManager(internal: ClassFileManager,
                                             external: Option[ClassFileManager])
      extends ClassFileManager {

    override def delete(classes: Array[File]): Unit = {
      external.foreach(_.delete(classes))
      internal.delete(classes)
    }

    override def complete(success: Boolean): Unit = {
      external.foreach(_.complete(success))
      internal.complete(success)
    }

    override def generated(classes: Array[File]): Unit = {
      external.foreach(_.generated(classes))
      internal.generated(classes)
    }
  }
```
  
And then allow a way to ease the instantiation of `ExternalHooks` that rely on an already existing instance, and removes all the ugly implementation from @smarter's code snippet.

**Comment by sjrd** [comment]
IMO the new API is more difficult than the previous one because it makes one critical mistake: it assumes that there is at most 1 external hook. This is why it's not composable, and why there is so much workaround in @smarter's code: basically it has to reimplement composability of external hooks.

Maybe we could try with an `externalHooks: List[ExternalHooks]` rather than `Option[ExternalHooks]`. Then maybe the boilerplate code of `patchIncOptions` could be simplified to just a `.addExternalHooks(dottyExternalHooks)`.

That said, I insist that we try to revert to the old API without *any* external hooks. There are probably exactly *3* users of this API in the world: Dotty, Scala.js and Scala Native, and at least 2 of them (@smarter and myself) agree that the old API was strictly superior, being simpler both for the implementation within sbt (presumably) and for the consumers of the API. Changing the API was probably meant to simplify Scala.js' use case by distilling what it was supposed to do, but obviously that experiment *failed*. Let's just revert to the old API, please.

**Comment by jvican** [comment]
With the new API in [here](https://github.com/sbt/zinc/pull/363), you can do:
```scala
  def dottyPatchIncOptions(incOptions: IncOptions): IncOptions = {
    val tastyFileManager = new ClassFileManager {
      private[this] val inherited = ClassFileManagerUtil.getDefaultClassFileManager(incOptions)

      def delete(classes: Array[File]): Unit = {
        val tastySuffixes = List(".tasty", ".hasTasty")
        inherited.delete(classes flatMap { classFile =>
          if (classFile.getPath endsWith ".class") {
            val prefix = classFile.getAbsolutePath.stripSuffix(".class")
            tastySuffixes.map(suffix => new File(prefix + suffix)).filter(_.exists)
          } else Nil
        })
      }

      def generated(classes: Array[File]): Unit = {}
      def complete(success: Boolean): Unit = {}
    }
    val newExternalHooks = incOptions.externalHooks.withClassFileManager(tastyFileManager)
    incOptions.withExternalHooks(newExternalHooks)
  }
```
  
I think that's one line less than the previous 0.13 implementation.
  
Reverting to the previous API was not an option because of time constraints. We are shipping the first RC before Monday, so now we're just double-checking. I think that my improvement to the API fixes the main issue with the new API designed by @romanowski: verbosity. Now, that should not be an issue.
  
Also note that Intellij and other IDEs may also be using this API.
  
Please, double-check and let me know if you're satisfied with my fix :smile:.

**Comment by sjrd** [comment]
I guess the "in here" link was meant to point to https://github.com/sbt/zinc/pull/363
