### ISSUE TITLE
Proposal: Incremental scaladoc

### ISSUE THREAD

**Issue by dwijnand** [sbt/zinc#387]
I don't think this is a heavily utilised use-case (has anyone invoked `~doc` before??). But perhaps implementing a safe, albeit rudimentary form of "incremental scaladoc" isn't _that_ much work.

Thoughts?

**Comment by jvican** [comment]
I also believe it wouldn't be much work. As discussed in sbt/sbt#3548, this would help for those folks running `publish` (because it runs `doc`) though one could argue that you'd prefer to avoid incremental compilation for both scaladoc and scalac when you want to publish artifacts to a public repository.
  
Feel free to tackle this one if you think it's important. I believe that most of the hard work is already there, you just need to make sure the phases compile with scaladoc. For that, you may need to change some parts of the bridge.

**Comment by dwijnand** [comment]
Thanks Jorge. I'll take your word that it won't be much work and consider doing it one hackathon.

**Comment by retronym** [comment]
Last I checked, the Scaladoc tool itself does not support incremental usage. The obvious part that needs work is incremental generation of the indices. Less obvious is support for `@inheritdoc` and substitution variables defined in comments of superclasses.

**Comment by jvican** [comment]
I know this is a little bit out of scope, Dale, but if you're interested in this you may also be interested in contributing a scaladoc tool based on the semanticdb. I know Olaf is doing some progress on this are with source code browsing, and if someone gets nice doc rendering working, you get incremental doc generation out of the box because the semanticdb is incremental and handles almost all the cases I can think scaladoc does in comparison with the mainstream compiler.

**Comment by jvican** [comment]
Linking to the work @Duhemm has done with Dottydoc, which has incremental compilation. Unless somebody is going to work on this, should we close this ticket @dwijnand ?

**Comment by dwijnand** [comment]
Sure. But did you mean to add a link there, to Dottydoc?

**Comment by jvican** [comment]
No, I just meant linking to the work he’s done in case people subscribed to this ticket are interested :)
