### ISSUE TITLE
Provide a migration guide for upgrading from 0.3.15

### ISSUE THREAD

**Issue by slandelle** [sbt/zinc#402]
Hi there,

I'm trying to find my way around based on [BaseCompilerSpec](https://github.com/sbt/zinc/blob/1.x/zinc/src/test/scala/sbt/inc/BaseCompilerSpec.scala), but I have to admit I'm a bit at a loss here.

Could you please provide a migration guide?
This way, I could upgrade [Gatling's standalone compiler](https://github.com/gatling/gatling/blob/master/gatling-compiler/src/main/scala/io/gatling/compiler/ZincCompiler.scala) and also help migrating [scala-maven-plugin](https://github.com/davidB/scala-maven-plugin/issues/208)?

Thanks in advance!

**Comment by jvican** [comment]
@slandelle Hello Stephane. There's no migration guide, and no plan for it. The amount of changes is insane, time is scarce, and I simply don't have the knowledge to provide a guide because a substantial portion of the changes were done before I arrived to this project.
  
If you're trying to upgrade Gatling's standalone compiler, I suggest you have a look at what other integrations like [sbt](https://github.com/sbt/sbt) or [Pants](https://github.com/pantsbuild/pants/tree/master/src/scala/org/pantsbuild/zinc) do. They do a great job at using the latest Java APIs. I recommend the Pants integration over the sbt one -- it's more isolated from the build tool and easier to read. By having a look at the Pants integration, migrations should be fairly easy.

**Comment by eed3si9n** [comment]
I've asked Stephane to file the issue here, and I think this is a reasonable request for former Zinc users. Can I remove the "wontfix" tag?

**Comment by jvican** [comment]
Sure. Tag has been removed.

**Comment by slandelle** [comment]
@jvican @eed3si9n Actually, I'm making good progress based on `IncrementalCompilerSpec` and friends. I'll let you know if I'm stuck, otherwise I'll close this, except if someone else needs help with upgrading.
Thanks for your great work!

**Comment by jvican** [comment]
@slandelle Great to hear that. I strongly suggest you to use the Pants integration instead though -- some of our testing infrastructure hasn't been updated to use our latest Java APIs. I've personally reviewed the Pants integration, so I can guarantee that it's up-to-date and it uses the best practices. I think it will save you time migrating and maintaining the code. [The integration is located here](https://github.com/pantsbuild/pants/tree/master/src/scala/org/pantsbuild/zinc).
