### ISSUE TITLE
Add a hook to filter out Scala options in every compile

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#406]
If scala options change from one run to the other one, Zinc recompiles the whole project conservatively.
  
With the advent of compilers like Dotty, Hydra and `rsc`, the current behaviour is too restrictive because some downstream users may want to filter out scalac options that are dependent to the way compilation should occur (like number of cores). This is safe to do because downstream users know which scala flags affect the compilation and which do not.
  
You can add this hook in `ExternalHooks` https://github.com/sbt/zinc/blob/1.x/internal/compiler-interface/src/main/java/xsbti/compile/ExternalHooks.java and https://github.com/sbt/zinc/blob/1.x/internal/compiler-interface/src/main/java/xsbti/compile/DefaultExternalHooks.java. The method `compile` in `IncrementalCompilerImpl` already takes an instance of `IncOptions`, which inside has an instance of `ExternalHooks`, so the last thing to do is to use the external hook we've just provided in the body of `makeConfig`, inside `MixedAnalyzingCompiler`: https://github.com/sbt/zinc/blob/1.x/zinc/src/main/scala/sbt/internal/inc/MixedAnalyzingCompiler.scala#L183-L214
  
/cc @dragos

**Comment by dragos** [comment]
Thanks @jvican! Even Scalac has several options that don't affect the output, so it would make sense to keep binaries. For instance `-verbose`, various `-Xprint` or logging options like -`Xlog-implicits`. 

The current behavior is inconvenient because in a multi-module project it would recompile upstream projects when adding such a logging option (for instance, trying to understand why an implicit is not selected in a downstream module).

But the main motivation is indeed the possibility to tweak when recompilation is not needed in other compilers :)

**Comment by romanowski** [comment]
:+1: 

We do similat thing when we are reusing compilation between intellij and gradle (since this was easier then aligning them - especially that for zinc even order of options provided is important)

**Comment by dwijnand** [comment]
Fixed in https://github.com/sbt/zinc/pull/548.
