### ISSUE TITLE
Use slf4j as the interface for logging

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#491]
Zinc is too entangled with log4j because of sbt. This leaks everywhere in the Zinc API and complicates the life of Zinc users because it's not possible to switch the implementation of the logger that Zinc uses. There is now a huge performance regression in Zinc because of log4j defaults and the current setup, see https://github.com/sbt/util/pull/68 and https://github.com/scala/scala/pull/6256#issuecomment-366142058.
  
I believe the best way to move forward, aside from fixing the underlying log4j bug, is to remove log4j from the interfaces so that downstream users can provide a lightweight implementation of a logger.
  
Slf4j is the standard logging interface in the JVM world.
  
What are your thoughts on this? I'd like to start a discussion about the feasibility of such a change and how it would be released. I'm happy to open a PR in sbt/zinc about this, but won't have time to take care of the sbt/sbt integration. @dwijnand @eed3si9n @retronym

**Comment by dwijnand** [comment]
I think it's a good idea, but am unsure if it's feasible: for instance I'm not sure if SLF4J's interface is sufficient to replace the current interface.

So I encourage the experimentation.

**Comment by eed3si9n** [comment]
I am open to all options, but log4j2 is supposed to be pretty fast, so I am guessing it's more to do with my current usage rather than log4j per se. 

For example, I implemented my own appender (https://github.com/sbt/util/blob/1.1.x/internal/util-logging/src/main/scala/sbt/internal/util/ConsoleAppender.scala) instead of using the AsyncAppender for quick migration from older code. That could be introducing contentions.

**Comment by dwijnand** [comment]
Probably never going to happen.
