### ISSUE TITLE
[1.4.x] MappedFileConverter.toVirtualFile is an allocation HotSpot

### ISSUE THREAD

**Issue by retronym** [sbt/zinc#769]
`path.toURI` and `String#replaceAllLiterallly` are expensive.

**Comment by retronym** [comment]
Consider:

  - `path.getFileSystem == FileSystems.default()` to see if the given path is a `file://`
  - precompiled regex rather than `replaceAllLiterally`.

**Comment by dwijnand** [comment]
> `path.toURI` and `String#replaceAllLiterallly` are expensive.

* in #802 I switched it to `Path#relativize`, string interpolation and `String#replace(Char)`
* in #820 I made `toPath(ref: VirtualFileRef): Path` try to reuse existing paths
* in #819 I'm proposing to keep the given `Path` instead of reconstituting it encoded paths and root paths

I'm thinking... optimistically closing this.

Re-open if you think there's more to do or want to double-check before closing and forgetting about this.
