### ISSUE TITLE
Should VirtualFileRef be ${SOME_STRING}/src/bar.scala instead of ${0}/src/bar.scala?

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#772]
@eatkins [wrote](https://github.com/sbt/sbt/pull/5521/files#r418405412):

Is `Seq[Path]` the right abstraction in `rootPaths`? It seems a bit strange that these are order dependent. I assume that the index into this Seq corresponds to the `${N}/path/to/file` in VirtualFileRefs? It seems like it might be a bit more robust to have virtual files that look like `${base}/path/to/file` instead at the cost of a modest increase in storage.

**Comment by eed3si9n** [comment]
Your right about Seq-index turning into to `VirtualFileRef#id`. I'm open on this design space.

My thought on this was that:

1. `VirtualFileRef` only needs to be stable across a single build. 
2. sbt should provide good enough default that works for 90% of the use cases (like Coursier cache).
3. Build authors should be able to append root paths easily.
4. Conversion between mapped `VirtualFileRef#id` back to `java.nio.file.Path` should be simple. (currently happening in https://github.com/sbt/zinc/blob/v1.4.0-M5/internal/zinc-core/src/main/scala/sbt/internal/inc/MappedVirtualFile.scala)

I thought using the order would be good enough, but maybe using String might allow for the VirtualFileRef to be more robust in the long term.

@retronym any suggestions here?

**Comment by eatkins** [comment]
Just to expand slightly, I see two minor issues with the current situation that are related but different:
1. Root paths are stored in a `Seq`. This raises a number of questions for me. Are there assumptions about the orderings of the paths? Would I break everything if I did `rootPaths := rootPaths.value.sorted`? What is the use case for adding additional rootPaths? How does zinc know about them? Does zinc try to relativize every path it sees against all of the root paths until it finds a match? What happens if an analysis file has files with N root paths and the build has N-1 or N+1 root paths (especially if a new path was prepended)?
2. Paths displayed in warnings have the id in them, e.g. `${0}/project/Scripted.scala`. I have to have knowledge of the virtual file to understand what that refers to (though I'm sure many users will at least be able to guess or deduce the meaning of `${0}`).

I really am just curious about the questions asked in (1).

To further elaborate on (2), I now see warnings that look like:
```
[warn] ${0}/project/Scripted.scala:92:28: object ClasspathUtilities in package classpath is deprecated (since 1.4.0): internal
[warn]     val loader = classpath.ClasspathUtilities.toLoader(scriptedSbtClasspath.files, noJLine)
[warn]                            ^
```
I think these would be more useful if either the id had a more descriptive name like `${base}` or if the path was expanded. I think this would help most for cases in which a path is displayed that isn't the in the project directory, like the coursier cache. Seeing something like `${4}/com/foo/bar/../blah.jar` would be somewhat difficult to track down. I actually like having shorter warnings without the full paths, but it does make debugging harder if I want to take action by copying the path.

In general, I think VirtualFiles are more of an implementation detail that should rarely be encountered by sbt end users except for the (I'm assuming) small subset of users who are implementing analysis file sharing for their team. As a normal end user, I'd expect to only see normal paths in logging. But I may also be missing something since I haven't been following the development of this feature carefully.

**Comment by eed3si9n** [comment]
> In general, I think VirtualFiles are more of an implementation detail that should rarely be encountered by sbt end users 

I agree.

> To further elaborate on (2), I now see warnings that look like...

There's a reporter I added so for normal compilation the compiler error should display normal path. So if the VirtualFile id is leaking out that might be a bug. Also for file loading [performance reason](https://github.com/sbt/zinc/issues/770) we might avoid passing `VirtualFile`s to Scala compiler layer as well.

> 1. Root paths are stored in a `Seq`. This raises a number of questions for me.
> Are there assumptions about the orderings of the paths?

`rootPaths` is preset with a `Seq(...)` and the index position would be used for `VirtualFileRef#id`. There's no inherent meaning in `${0}` etc.

> Would I break everything if I did `rootPaths := rootPaths.value.sorted`?

It shouldn't break anything. It would shuffle the number around so it would invalidate your previous compilation, but that's about it.

> What is the use case for adding additional `rootPaths`?

The purpose of the `rootPaths` is to remove machine dependence. One might add additional `rootPaths` if they include sources or JAR files outside of the preset places.

> How does zinc know about them?

There's a preset `rootPaths`. Beyond that, build tools can pass that into Zinc.

> Does zinc try to relativize every path it sees against all of the root paths until it finds a match?

Yes. That behavior is configurable, but in general yes.

> What happens if an analysis file has files with N root paths and the build has N-1 or N+1 root paths (especially if a new path was prepended)?

If you previously created `${0}/src/bar.scala`, and now it's supposed to be `${1}/src/bar.scala` or something then I guess it would result to invalidation of the file.
