### ISSUE TITLE
no-op compilation doesn't fire CompileProgress#earlyOutputComplete

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#847]
## steps

1. Create subprojects `dep` and `use` with pipelining (I have it locally)
2. `use/checkPickle`
3. `use/checkPickle` 

```scala
    TaskKey[Unit]("checkPickle") := {
      val s = streams.value
      val x = (dep / Compile / compile).value
      val pkl = (dep / Compile / pickleProducts).value
      s.log.info(s"pkl = $pkl, x = $x")
    },
```

## problem

Second `checkPickle` gets stuck indefinitely because the second time `dep/compile` is a no-op, and `CompileProgress#earlyOutputComplete` is not fired. 

## expectation

Fire `CompileProgress#earlyOutputComplete(...)` even for no-op compilation.

## note

Similar situation can occur in the following scenario:

1. `compile`
2. make some edits to `dep` subproject
3. `compile`

**Comment by dwijnand** [comment]
Sounds like a naming problem to me.  As in "earlyOutputComplete" not firing because no compilation occurred sounds correct, but I can understand how you're using it as the trigger point.  So you want the other behaviour, but then it shouldn't be "earlyOutputComplete" IMO. 👨‍🎨

"picklesReady" would (apart from sound funny to say) be a little too implementation-specific (I assume sbt-dotty will by emitting and using TASTy?).  `typecheckingMetadataReady`?  Seb once explained that TASTy contains the code after all "elaboration" is done, so something like `elaborationReady` or `elaborationDone`/`compileElaborationDone`/...?

Or maybe just `earlyOutputReady`, now that I think about it.  "Complete" implies to me like more than "noop" work was done, for some reason, while "ready" is agnostic to that.  "Let me know when that early output is ready." "It's ready." vs "Let me know when that early output is complete." "It's complete."  🤔

**Comment by eed3si9n** [comment]
<s>While fixing this I also found a bug that it was completing prematurely when there are multiple cycles.</s>

"complete" I think is ok in part because the other side is waiting on a Promise, and Promise API tends to use the word "complete". Also note that `earlyOutputComplete(success = false)` is a valid call. `ready(success = false)` may be confusing?

**Comment by dwijnand** [comment]
The promise implementation is detail on the implementation side, the API is agnostic to that.  I'm wondering if the confusion on whether "output" is the verb "to output" or the noun "the output"?  I think of the noun.  `earlyOutputComplete(success = false)` only makes sense when you're thinking "Promise implementation" otherwise how can something be complete but unsuccessful??  I guess you can successfully complete a task (do a quiz) but the _result_ isn't a success (you failed the quiz), and the confusion is there?  I guess "complete" is also an adjective and a verb...

**Comment by eed3si9n** [comment]
Would `afterEarlyOutput(success = false)` clarify that it's an event handler communicating some timing?

**Comment by dwijnand** [comment]
Yeah, sounds good to me.
